# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_p/date_range.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from typ_p import date_pb2 as typ__p_dot_date__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16typ_p/date_range.proto\x12\x05typ_p\x1a\x10typ_p/date.proto\"\\\n\ndate_range\x12(\n\tdate_from\x18\x01 \x01(\x0b\x32\x0b.typ_p.dateR\x08\x64\x61teFrom\x12$\n\x07\x64\x61te_to\x18\x02 \x01(\x0b\x32\x0b.typ_p.dateR\x06\x64\x61teToB,Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_p.date_range_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_p'
  _globals['_DATE_RANGE']._serialized_start=51
  _globals['_DATE_RANGE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
