# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_p/date_delta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16typ_p/date_delta.proto\x12\x05typ_p\"\\\n\ndate_delta\x12\x12\n\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n\x05month\x18\x02 \x01(\x05R\x05month\x12\x12\n\x04week\x18\x03 \x01(\x05R\x04week\x12\x10\n\x03\x64\x61y\x18\x04 \x01(\x05R\x03\x64\x61yB,Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_p.date_delta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_p'
  _globals['_DATE_DELTA']._serialized_start=33
  _globals['_DATE_DELTA']._serialized_end=125
# @@protoc_insertion_point(module_scope)
