# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_p/uuid.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10typ_p/uuid.proto\x12\x05typ_p\"\x1a\n\x04uuid\x12\x12\n\nuuid_value\x18\x01 \x01(\x0c\x42,Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_p.uuid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_p'
  _globals['_UUID']._serialized_start=27
  _globals['_UUID']._serialized_end=53
# @@protoc_insertion_point(module_scope)
