# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typ_p/value.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from typ_p import date_delta_pb2 as typ__p_dot_date__delta__pb2
from typ_p import date_range_pb2 as typ__p_dot_date__range__pb2
from typ_p import date_time_pb2 as typ__p_dot_date__time__pb2
from typ_p import date_pb2 as typ__p_dot_date__pb2
from typ_p import number_pb2 as typ__p_dot_number__pb2
from typ_p import uuid_pb2 as typ__p_dot_uuid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11typ_p/value.proto\x12\x05typ_p\x1a\x16typ_p/date_delta.proto\x1a\x16typ_p/date_range.proto\x1a\x15typ_p/date_time.proto\x1a\x10typ_p/date.proto\x1a\x12typ_p/number.proto\x1a\x10typ_p/uuid.proto\"\xc0\x03\n\x05value\x12\x1f\n\nbool_value\x18\x01 \x01(\x08H\x00R\tboolValue\x12#\n\x0cstring_value\x18\x02 \x01(\tH\x00R\x0bstringValue\x12!\n\x0b\x62ytes_value\x18\x03 \x01(\x0cH\x00R\nbytesValue\x12,\n\nuuid_value\x18\x04 \x01(\x0b\x32\x0b.typ_p.uuidH\x00R\tuuidValue\x12\x32\n\x0cnumber_value\x18\x05 \x01(\x0b\x32\r.typ_p.numberH\x00R\x0bnumberValue\x12:\n\x0f\x64\x61te_time_value\x18\x08 \x01(\x0b\x32\x10.typ_p.date_timeH\x00R\rdateTimeValue\x12,\n\ndate_value\x18\t \x01(\x0b\x32\x0b.typ_p.dateH\x00R\tdateValue\x12=\n\x10\x64\x61te_range_value\x18\n \x01(\x0b\x32\x11.typ_p.date_rangeH\x00R\x0e\x64\x61teRangeValue\x12\x37\n\x0c\x61rray_values\x18\x0b \x01(\x0b\x32\x12.typ_p.array_valueH\x00R\x0b\x61rrayValuesB\n\n\x08value_of\"3\n\x0b\x61rray_value\x12$\n\x06values\x18\x01 \x03(\x0b\x32\x0c.typ_p.valueR\x06values*\xf7\x01\n\tValueType\x12\x16\n\x12VALUE_TYPE_UNKNOWN\x10\x00\x12\x13\n\x0fVALUE_TYPE_BOOL\x10\x01\x12\x15\n\x11VALUE_TYPE_STRING\x10\x02\x12\x14\n\x10VALUE_TYPE_BYTES\x10\x03\x12\x13\n\x0fVALUE_TYPE_UUID\x10\x04\x12\x15\n\x11VALUE_TYPE_NUMBER\x10\x05\x12\x17\n\x13VALUE_TYPE_DATETIME\x10\x06\x12\x13\n\x0fVALUE_TYPE_DATE\x10\x07\x12\x19\n\x15VALUE_TYPE_DATE_RANGE\x10\x08\x12\x1b\n\x17VALUE_TYPE_ARRAY_VALUES\x10\nB,Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_pb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typ_p.value_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z*gitlab.com/mippo.app/typ-p.git/go/pb/typ_p'
  _globals['_VALUETYPE']._serialized_start=660
  _globals['_VALUETYPE']._serialized_end=907
  _globals['_VALUE']._serialized_start=156
  _globals['_VALUE']._serialized_end=604
  _globals['_ARRAY_VALUE']._serialized_start=606
  _globals['_ARRAY_VALUE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
